# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175ddbb62b1159743459dfea8230b5e64eb65e25d7ab8e104e3a5e0ea20d9558b95efbb8f6635017908843cacdeb748dd3fe00c61688fa67cb6af011ac6eaa96

test:
  secret_key_base: 5354f67d6e86d4f90ee31849203a4333f99b28271615946462d4cb6773bf123a0a041939aa557a9bd5af9f6eb734ef0759b814050b1f109e72c787e6cdeed032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
